### ISSUE TITLE
Possible cross site scripting

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/vines#48]
`first_name` and /or `last_name` could be used to inject code.

The PR was not released, yet. Nevertheless it should be fixed asap! 

related to #46

**Comment by jhass** [comment]
I'm not sure how XSS is a backend issue, the frontend shouldn't allow it IMO.

**Comment by Zauberstuhl** [comment]
er.. well I wanted to report it in jsxc .. was maybe too late yesterday :)
