### ISSUE TITLE
External clients only?

### ISSUE THREAD

**Issue by hfroese** [diaspora/vines#76]
The XMPP server seems to work - but with external clients only.
Can't sign in at Diaspora web page.
Message: "Keine Verbindung. Neu anmelden"
No errors in log file.
![bildschirmfoto vom 2015-12-02 20 26 44](https://cloud.githubusercontent.com/assets/1968490/11543150/5db53b78-993b-11e5-9f01-46b7c5870df4.png)

**Comment by Zauberstuhl** [comment]
hi, which pod?

**Comment by hfroese** [comment]
Ich nehme an, dass du auch Deutsch verstehst? 
Es geht um https://pod.hfrc.de
Verbindungen von Pidgin funktionieren, nur auf der Webseite wird folgendes angezeigt:
![bildschirmfoto vom 2015-12-03 00 33 19](https://cloud.githubusercontent.com/assets/1968490/11547607/820c3732-9955-11e5-828b-e8314a80fe3b.png)

**Comment by Zauberstuhl** [comment]
according to our chat I'll close this
