### ISSUE TITLE
Attempt to unlock a mutex which is locked by another thread

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/vines#8]
Seams like a random bug with ruby-2.0.0:

https://bugs.ruby-lang.org/issues/9132
https://bugs.ruby-lang.org/issues/9432

According to eventmachine/eventmachine#457 that should be fixed with `ruby-2.0.0-p451`.
But I can see it still with `ruby-2.0.0p481`

**Comment by Zauberstuhl** [comment]
to prove him wrong -> https://github.com/diaspora/vines/pull/26#issuecomment-55536411

**Comment by jhass** [comment]
Heh...
